unstable_features = true

combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 16
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
max_width = 100
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 16
use_field_init_shorthand = true
wrap_comments = true
